[[mgr.prepend_keymap]]
on   = "i"
run  = "arrow -1"
desc = "up"

[[mgr.prepend_keymap]]
on   = "k"
run  = "arrow 1"
desc = "down"

[[mgr.prepend_keymap]]
on   = "j"
run  = "leave"
desc = "left"

[[mgr.prepend_keymap]]
on   = "h"
run  = "inspect"
desc = "instpect"

