[[mgr.prepend_keymap]]
on   = "i"
run  = "arrow -1"
desc = "up"

[[mgr.prepend_keymap]]
on   = "k"
run  = "arrow 1"
desc = "down"

[[mgr.prepend_keymap]]
on   = "j"
run  = "leave"
desc = "left"

[[mgr.prepend_keymap]]
on   = "h"
run  = "inspect"
desc = "instpecti"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
